### ISSUE TITLE
Add Support for Square meme

### ISSUE THREAD

**Issue by Chad-Petersen** [ibonwe/polygon-memes-generator#11]
It would be great if we could add the ability to generate square memes as well. Currently we only support triangles. A square meme would only require to specify the character and one of the dimensions of the square. We will need to think of the interface we will present to the user. Where the user will be able to suggest which meme they want to select, and based on there selection would be asked for a character and dimension such as height or width and the generator then produces the meme. @HackerGal how do you think we should ask the user for this information?

**Comment by HackerGal** [comment]
I think we should ask the user which shape they would like the meme generator to create. Once they select this, we then let the relevant requests for information, pop up..

**Comment by Chad-Petersen** [comment]
@HackerGal yes that is true. Currently I have just simply asked the user to enter the name of the shape they want to generate. It is not the best way to solve it. But I think we can maybe create a different issue that can focus primarily on solving that the best way possible. I think this issue should only focuses on adding square support which pull request #13 does.

**Comment by HackerGal** [comment]
This issue has been resolved in pull request #13.
