### ISSUE TITLE
Add Support for Right-Angled Triangle meme

### ISSUE THREAD

**Issue by Chad-Petersen** [ibonwe/polygon-memes-generator#5]
Create the ability to display a right angled triangle of a given character and of a given height. The user should be able to to get a prompt asking for the two previously mentioned input. And a triangle should be generated of the appropriate dimension and character value. However modify the functionality to ask the user which type of triangle they would want to have generated for them.

**Comment by HackerGal** [comment]
Which type of triangle? As in, obtuse, acute(or reflex)? Then shouldn't we rename the branch?

**Comment by Chad-Petersen** [comment]
@HackerGal A right angled triangle as the pull request suggest.

I was thinking the following right angled triangle would be great to produce:

`*`
`**`
`***`
`****`
`*****`

I hope the above clears things up a bit for you?

**Comment by Chad-Petersen** [comment]
This has been resolved in pull request #21.
