### ISSUE TITLE
Specify triangle direction

### ISSUE THREAD

**Issue by Chad-Petersen** [ibonwe/polygon-memes-generator#7]
I would like to as a user also specify the direction in which the triangle should be generated. Ideally the user should have the ability to specify between four directions namely -up, down, left and right. This will then print out the triangles with the head of the triangle facing the direction specific by the user.

**Comment by HackerGal** [comment]
Last week, you said that you want the new direction to be added to the old triangle. Do you still want that?

**Comment by Chad-Petersen** [comment]
@HackerGal I don't get what it is that you mean by that? I think it would be nice to have the ability to specify the direction of the triangle. So maybe ticket is a bit big -we can break it down into smaller issues and this could be a milestone? But essentially the user should give an extra parameter and that is direction and from that we must now how to build the specified triangle. I think we might need to spilt up the code so that we can have a new file for each triangle type and in each triangle type file -maybe add different functions to generate in different directions. What do you think @HackerGal?

**Comment by HackerGal** [comment]
I will forward that message to you if I can find it. For now I'm going to concentrate on the issues in this thread. I agree with creating new files for new triangle types, should be fun. Just point it out if I'm going off track. I might not realise that I am.

**Comment by HackerGal** [comment]
I added one triangle. Did I do it correctly?

**Comment by Chad-Petersen** [comment]
I am closing this issue for now since this issue is too big to resolve all in one go. I suggest we have a think about this in at a later stage. Lets create a milestone for this and plan how we should approach this first.
