### ISSUE TITLE
Inform user how to exit

### ISSUE THREAD

**Issue by HackerGal** [ibonwe/polygon-memes-generator#8]
The user is not informed that typing "-1" will exit the program. This needs to be fixed.

**Comment by Chad-Petersen** [comment]
I suggest how about we Display a welcome message to the user before we get into the do-while loop. And in that welcome message we can tell the user -what the program does and how to exit the program as follows. "Welcome to **iBonWe Triangle Memes Generator**. This is an awesome Triangle Memes generator. You can create as many triangle memes as you want but if you want to stop at any time enter (-1) for height." . What do you think? Maybe change up a few words at your discretion.

**Comment by HackerGal** [comment]
I love it! Maybe we should do this after I've attempted the other two issues? Right now, with the current program, that message is a little misleading, lol.

**Comment by Chad-Petersen** [comment]
Lol that is true. But I think this is a quick fix and can quickly be implemented. Lets try and get this fix out first. A user won't be able to know how to stop the program. So I think it is much better to first get this in so that this bug is fixed before we add new functionality -that can take time.

**Comment by Chad-Petersen** [comment]
@HackerGal I think the stop should be put on the first option and not height. The first option will be the shape that we want to select. Maybe one of the options should be "Stop". Lol, there is thankfully no polygon shape named "Stop" :). What do you think?

**Comment by HackerGal** [comment]
I added the above, what do you think?

**Comment by HackerGal** [comment]
Shall we ask the user after the welcome msg if they want to continue or to stop?

**Comment by Chad-Petersen** [comment]
This issue has been resolved in pull request #17.
